### ISSUE TITLE
Form creation and view UI

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/open-source-programs-web#6] opened 2020-05-19 16:41 UTC
## Description
As an Admin,
I am able to create forms,
so that users can fill them in. I'm also able to view this form from users perspective to fill in the questions.

## Mocks
*Need to be created*

### Update [Required]
- [x] Button to open the Form create UI
- [x] UIs for different type of questions
- [x] Button to add a new question
- [x] Button to remove a question
- [x] Button to publush a form
- [x] UI to view all the question from a users perspective

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

**Comment by bismitaguha** [comment] 2020-05-22 13:43
### Initial View
![OSP-UI-Applicant Progress-Student Side (1)](https://user-images.githubusercontent.com/43119923/82673902-259c1180-9c60-11ea-9bb2-6961dd6f8bb3.png)

**Comment by mayburgos** [comment] 2020-05-22 17:22
@bismitaguha Two things to add: 
* Back button ( < Back to All Forms)
* Horizontal line (between the form and the edit form)

**Comment by bismitaguha** [comment] 2020-05-22 21:14
### Updated View
![OSP-UI-Applicant Progress-Student Side (2)](https://user-images.githubusercontent.com/43119923/82709902-42a40500-9c9f-11ea-9327-cdddb6bcf919.png)

@mayburgos @Monal5031 This is the revised view. Please review!!! :smiley:

**Comment by bismitaguha** [comment] 2020-05-23 14:01
### Form List
![OSP-UI-Form list](https://user-images.githubusercontent.com/43119923/82732623-e935e780-9d2b-11ea-929a-a99cc6284d1c.png)

**Comment by Monal5031** [comment] 2020-05-25 13:12
One suggestion for the button texts, Instead of `Update`, IMO we should use `Edit` 

Also, instead of having separate column for buttons, how about just using icons at the top right corner of the form box.

And I think we are missing a link copy button or field to help us copy the link to share with others.

**Comment by bismitaguha** [comment] 2020-05-27 18:09
## Updated Form Creation View
- **Change to normal button from ghost button for EDIT**
I feel that edit is not an action which we don't want the admin to perform, neither do we need alerts for that action. So it should not be a Ghost Button
- **Adding of REQUIRED and Specific entry for Choice, Dropdown and Checkbox fields**
There was no discussion regarding the **REQUIRED** option for the form. I feel it's an important feature, hence an addition. @Monal5031 I have updated the [DB structure](https://whimsical.com/54vvNLcoYqHzeFqEpyPAKq) with the required feature.

![OSP-UI-Form Creation (1)](https://user-images.githubusercontent.com/43119923/83057022-f7f60480-a073-11ea-8097-bad19e0c166b.png)

## View for Form Preview
This view will be similar to what users view. Based on the data type for each question, it will be rendered in the frontend.
![OSP-UI-Form Preview (1)](https://user-images.githubusercontent.com/43119923/83057036-fc222200-a073-11ea-9e3a-312bef0d4365.png)

@mayburgos @Monal5031 @abha224 Please provide suggestions. :grinning:

**Comment by abha224** [comment] 2020-05-28 06:45
@bismitaguha 
For the form creation page: The required field is a good addition. Will the enter options field available for all the data types? Also, I think the edit button seems redundant as the form is displayed in the editing mode below.
Form previews looks good :+1:

**Comment by bismitaguha** [comment] 2020-05-28 11:04
@abha224 the top 3 buttons are for the form, like deleting the whole form, updating it's name or target users, etc.
I have separated them by a horizontal line.
The 2 options below are for the fields only. **SAVE** would save any new fields created. For updating a specific one respective icons for each field is there, and **PREVIEW** does it's obvious.

Also since @abha224 couldn't realize the obvious from the design, it's a flaw. I feel a change would be extending the form card, and putting icons for Publish, Edit and Delete. @mayburgos @Monal5031 Please suggest!

**Comment by bismitaguha** [comment] 2020-05-28 11:18
@abha224 
>  Will the enter options field available for all the data types?

No that will be disabled for other fields. If Checkbox, choice or dropdown is selected that will be enabled.

**Comment by abha224** [comment] 2020-05-29 13:51
@bismitaguha Oh, alright. thanks for clarifying!

> I feel a change would be extending the form card, and putting icons for Publish, Edit and Delete. 

I agree to this, it seems more intuitive as well. 

> No that will be disabled for other fields. If Checkbox, choice or dropdown is selected that will be enabled.

cool, I was just confirmed as the UI mockup had it for all the questions :+1:

**Comment by bismitaguha** [comment] 2020-05-30 21:12
### Updated Form Views
![OSP-UI-Form page](https://user-images.githubusercontent.com/43119923/83338949-b1f4a700-a2e6-11ea-8888-2ea9bfaa1fee.png)
![OSP-UI-Form Preview (3)](https://user-images.githubusercontent.com/43119923/83339126-40b5f380-a2e8-11ea-9358-89d2a8ab868c.png)
![OSP-UI-Form Creation (4)](https://user-images.githubusercontent.com/43119923/83339128-427fb700-a2e8-11ea-9d8e-8b19995e7c4f.png)

**Comment by abha224** [comment] 2020-08-31 16:13
Closing this issue as the associated UI code has been merged.

**Closed by abha224** 2020-08-31 16:13 UTC
Labels: Category: User Interface, Program: GSOC
