### ISSUE TITLE
Add frontend support for making admin

### ISSUE THREAD

**Issue by ruddi10** [anitab-org/open-source-programs-web#116] opened 2021-03-08 11:23 UTC
### Is your feature request related to a problem? Please describe.
I want to implement frontend support for promoting or demoting a user. Currently we have to go to the django admin and change user type from there that I feel is a cumbersome task.

### Describe the solution you'd like
I plan on giving one more option named Users on the admin dashboard which will have a list of users with their position and a button to either promote a student to admin or demote an admin to a student.

**Comment by ruddi10** [comment] 2021-03-08 11:23
Kindly assign this issue to me @Aaishpra  @codesankalp

**Comment by keshakaneria** [comment] 2021-03-08 11:38
> Kindly assign this issue to me @Aaishpra @codesankalp

Hey @ruddi10! Thats great that you have raised an issue. I would like to tell you that whenever anyone raises an issue, it needs to be approved by atleast 1 member of the OS Leaders or the admins after which they will assign the issue whoever wants to work on it. Since you have created this issue, let us identify if the issue really needs to be worked upon. Till the time you can work on other issues 😄 If you have any queries you can catch us on [Zulip](https://anitab-org.zulipchat.com/#).
All the best 🎉

**Comment by Aaishpra** [comment] 2021-03-08 11:40
@ruddi10 i like the idea and motivation behind this issue, but currently we are focusing on completion of MVP and I don't think there is a need of this type of feature in the application which can promote a student to admin or demote the admin to student, basically this is an open source programs management application made for managing gsoc and other programs, so I don't particularly see any use of this feature.
But you can still propose this idea in upcoming open session of this project and see what others think of this or propose this idea in your gsoc proposal😉

**Comment by ruddi10** [comment] 2021-03-08 11:48
> > Kindly assign this issue to me @Aaishpra @codesankalp
> 
> Hey @ruddi10! Thats great that you have raised an issue. I would like to tell you that whenever anyone raises an issue, it needs to be approved by atleast 1 member of the OS Leaders or the admins after which they will assign the issue whoever wants to work on it. Since you have created this issue, let us identify if the issue really needs to be worked upon. Till the time you can work on other issues 😄 If you have any queries you can catch us on [Zulip](https://anitab-org.zulipchat.com/#).
> All the best 🎉

Yes I just wanted to raise a issue and want to make sure that incase this issue need to be worked upon to assign it to me so that I can work on it as I have a a basic outline of the code ready in my mind 😁

**Comment by keshakaneria** [comment] 2021-03-08 11:52
> Yes I just wanted to raise a issue and want to make sure that incase this issue need to be worked upon to assign it to me so that I can work on it as I have a a basic outline of the code ready in my mind 😁

Yayy! Thats great :) dont worry, we can discuss this in upcoming meetings so we can understand the idea more better 😄

**Comment by ruddi10** [comment] 2021-03-08 12:03
> @ruddi10 i like the idea and motivation behind this issue, but currently we are focusing on completion of MVP and I don't think there is a need of this type of feature in the application which can promote a student to admin or demote the admin to student, basically this is an open source programs management application made for managing gsoc and other programs, so I don't particularly see any use of this feature.
> But you can still propose this idea in upcoming open session of this project and see what others think of this or propose this idea in your gsoc proposal😉

Actually I meant for anyone registered on that app

**Comment by codesankalp** [comment] 2021-03-08 12:12
@ruddi10 Looks good but giving permissions to all newly registered to change their user_type to admin is not feasible. But Yeah features like admins can make admins is possible. This issue needs discussion first with the admins.

**Comment by ruddi10** [comment] 2021-03-08 12:21
Anyone cannot change their user type. I am not suggesting such a change. It will be an approval based system one can apply to be an admi then their request will be send to the admin who can approve it and once approved they will be admin , incase its rejected there request will fail.

**Comment by codesankalp** [comment] 2021-03-08 12:29
@ruddi10 But why give this permission to all users for applying as an admin? As the admin count is fixed and small in the count, I don't think it will be a good feature to apply for an admin position from the web.

**Comment by ruddi10** [comment] 2021-03-08 12:43
Then we can atleast provide admin with a feature to make others admin. Alongwith it we can even think of implement the option of inviting some person as admin. @codesankalp  @isabelcosta

**Comment by codesankalp** [comment] 2021-03-08 12:46
Yes, this is the thing I am suggesting and that can be done. But as mentioned this issue needs discussion.

**Comment by codesankalp** [comment] 2021-03-20 14:12
Closing this as it is duplicate of https://github.com/anitab-org/anitab-forms-web/issues/4

**Closed as completed by codesankalp** 2021-03-20 14:12 UTC
Labels: Status: On Hold
