### ISSUE TITLE
feat: Replace class components and states with functional components and hooks

### ISSUE THREAD

**Issue by shruti1421** [anitab-org/open-source-programs-web#69] opened 2021-01-29 19:20 UTC
### Is your feature request related to a problem? Please describe.
-As we know it was very difficult to write code by using class components in a react app of having such a large code base. 
-Also in many sections of the code this.state and this.props is used a lot of times so, to make the code look cleaner we can destructure the props and states.

### Describe the solution you'd like
-In my opinion we can use functional components and hooks in all the components of this React App. 
-Destructing of props and states wherever it is needed.
This will increase the readability of the code and make the code to look cleaner.   

I would like to make this changes as mentioned above in login and register page.

**Comment by ayan-biswas0412** [comment] 2021-02-13 14:29
@shruti1421 I also agree with you , I want to contribute in this issue also for the other pages in the repo.

**Comment by Aaishpra** [comment] 2021-02-18 06:49
Duplicate of #76

**Closed as completed by Aaishpra** 2021-02-18 06:49 UTC
