### ISSUE TITLE
Create the config.yml file for the Welcome Bot.

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-web#87] opened 2021-02-16 15:11 UTC
## Description
As a first time contributor,
I need a bot to help guide my first contribution,
so that I can follow this org's contribution guidelines.

## Mocks
![image](https://user-images.githubusercontent.com/66437295/108081672-3797cd00-7097-11eb-85c3-8ba3fbda2d3b.png)

### Update [Required]
- [ ] newIssueWelcomeComment is complete with the correct links to this repo.
- [ ] newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
- [ ] firstPRMergeComment is complete.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

**Comment by Amulya-coder** [comment] 2021-02-16 15:12
@isabelcosta can you please add labels to this issue. Thanks 😊.

**Comment by Aaishpra** [comment] 2021-02-17 12:15
@Amulya-coder this is a duplicate of #59 if you want to work on #59 can you comment there and close this issue.

**Comment by aditmehta9** [comment] 2021-02-18 06:41
Closing this issue because it is dupliacte

**Closed as completed by aditmehta9** 2021-02-18 06:41 UTC
